name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

# Only allow one docs build at a time so that overlapping stale builds will get
# cancelled automatically.
concurrency:
  group: deploy_docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write  # so we can write to github pages without a token

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: tlambert03/setup-qt-libs@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "napari[all]"
          python -m pip install -e ".[doc]"

      - name: Build Docs
        uses: aganders3/headless-gui@v2
        with:
          run: make docs

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/_build
          publish_branch: gh-pages
